fix: insert protobuf.dylib according cibuildwheel github issue comments

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -130,24 +130,28 @@ jobs:
         CIBW_REPAIR_WHEEL_COMMAND_WINDOWS: "delvewheel repair --add-path C:/Windows/System32 --add-path C:/vcpkg/installed/x64-windows/bin -w {dest_dir} {wheel}"
     
 
-        CIBW_REPAIR_WHEEL_COMMAND_MACOS: |
-          pip install delocate
+        # CIBW_REPAIR_WHEEL_COMMAND_MACOS: |
+        #   pip install delocate
 
-          echo "== Repairing wheel with delocate =="
-          delocate-wheel -w {dest_dir} -v {wheel}
+        #   echo "== Repairing wheel with delocate =="
+        #   delocate-wheel -w {dest_dir} -v {wheel}
 
-          echo "== Injecting libprotobuf.dylib (in case it's missing) =="
-          for whl in {dest_dir}/*.whl; do
-            if ! delocate-listdeps "$whl" | grep -q "libprotobuf.dylib"; then
-              echo "---> Injecting libprotobuf.dylib manually..."
-              delocate-add-dylib -L /Users/runner/protobuf/lib/libprotobuf.dylib -w {dest_dir} "$whl"
-            else
-              echo "---> libprotobuf.dylib already present"
-            fi
-          done
+        #   echo "== Injecting libprotobuf.dylib (in case it's missing) =="
+        #   for whl in {dest_dir}/*.whl; do
+        #     if ! delocate-listdeps "$whl" | grep -q "libprotobuf.dylib"; then
+        #       echo "---> Injecting libprotobuf.dylib manually..."
+        #       delocate-add-dylib -L /Users/runner/protobuf/lib/libprotobuf.dylib -w {dest_dir} "$whl"
+        #     else
+        #       echo "---> libprotobuf.dylib already present"
+        #     fi
+        #   done
 
-          echo "== Final dependencies =="
-          delocate-listdeps {dest_dir}/*.whl
+        #   echo "== Final dependencies =="
+        #   delocate-listdeps {dest_dir}/*.whl
+
+        CIBW_REPAIR_WHEEL_COMMAND_MACOS: >
+          DYLD_LIBRARY_PATH=DYLD_LIBRARY_PATH=/Users/runner/protobuf/lib:$DYLD_LIBRARY_PATH delocate-listdeps {wheel} &&
+          DYLD_LIBRARY_PATH=DYLD_LIBRARY_PATH=/Users/runner/protobuf/lib:$DYLD_LIBRARY_PATH delocate-wheel --require-archs {delocate_archs} -w {dest_dir} {wheel}
 
 
         CIBW_CMAKE_CONFIGURE_OPTIONS: ${{ matrix.os == 'windows-latest' && '-DCMAKE_TOOLCHAIN_FILE=C:/vcpkg/scripts/buildsystems/vcpkg.cmake;-DVCPKG_TARGET_TRIPLET=x64-windows' || '' }}
