fix: attempt to install proto in global path

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -203,9 +203,15 @@ jobs:
             DETECTED_ARCH=$(uname -m)
             echo "Detected architecture: $DETECTED_ARCH"
          
-            export BOOST_ROOT=$(brew --prefix boost)
-            export CXXFLAGS="-I$BOOST_ROOT/include -I/Users/runner/protobuf3/include"
-            export LDFLAGS="-L$BOOST_ROOT/lib -L/Users/runner/protobuf3/lib"
+            # export BOOST_ROOT=$(brew --prefix boost)
+            # export CXXFLAGS="-I$BOOST_ROOT/include -I/Users/runner/protobuf3/include"
+            # export LDFLAGS="-L$BOOST_ROOT/lib -L/Users/runner/protobuf3/lib"
+            export PATH="/usr/local/bin:$PATH" &&
+            export LD_LIBRARY_PATH="/usr/local/lib:$LD_LIBRARY_PATH" &&
+            export CMAKE_PREFIX_PATH="/usr/local" &&
+            ldconfig &&
+            # Debug Protobuf installation
+            protoc --version || echo "Protoc not found"
             #echo "Protobuf installed at $(brew --prefix protobuf)"
             protoc --version
             echo "--------------------END DEBUG --------------------------"	
